#### 1. 임의의 정수를 입력받아 각 자리의 숫자 중 홀수 값의 총합을 계산하는 함수를 만들어보세요.
예) 6753 -> 15 출력

In [1]:
def sum_place_value():
    num = input('숫자를 입력하세요: ')
    sum = 0
    for i in range(0,(len(num))):
        if int(num[i]) % 2 == 1:
            sum = sum + int(num[i])
    return sum

sum_place_value()

숫자를 입력하세요: 3958


17

#### 2. 숫자 야구 게임을 만들어 봅시다
*구글링을 통해 참고할 수 있는 코드가 많지만 꼭 본인의 힘으로 해봅시다 !!*

**Game Rule**
- 임의의 세 자리수 숫자를 맞추는 게임입니다!
- 숫자는 0이 존재하면 안되며, 중복된 수가 없어야 합니다
- 일치하는 숫자가 존재하지만, 위치가 다를 경우 `Ball`
- 일치하는 숫자가 존재하며 위치도 같을 경우 `Strike`
- 숫자와 위치가 모두 다른 경우 `Out`
- `3 Strike` 이면 정답이며, `3 Out` 전에 숫자를 맞춰야 합니다 !
- 기회는 `총 10번` 입니다

**힌트**
- **`input()`**을 사용하여 사용자로 부터 매 차례 숫자를 입력 받습니다
- **`while문`**을 사용하여 게임을 반복합니다
- **`for문`**과 **`if문`**을 사용하여 정답과 입력 받은 숫자를 순회하며 각 자리수를 비교합니다
- 차례가 끝날 때 마다 `Ball`, `Strike`, `Out` 현황을 **`print()`** 하여 알려줍니다
-  `Ball`과 `Strike`는 매 차례마다 초기화 되어야 하지만 `Out`은 누적됩니다
- 정답일 경우와 패배일 경우 **`break문`**을 사용하여 **`while문`**을 탈출합니다

In [2]:
### 자리수가 전부 다른 세자리 숫자 난수 생성

import numpy as np

while True:
    ans = np.random.randint(100,1000)
    if '0' not in str(ans):
        if str(ans)[0] != str(ans)[1]:
            if str(ans)[0] != str(ans)[2]:
                if str(ans)[1] != str(ans)[2]:
                    break

ans

623

In [3]:
# 하루 종일 해도 안되는 걸로 보아 소질이 없나봐요

#### 3. 다음 오바마 연설문을 불러오는 코드를 실행 시키고 문제를 풀어보세요

In [4]:
import requests

url = 'http://cfile221.uf.daum.net/attach/1332E3064975C0E70F1AFF' ## 오바마 연설문 화일
res = requests.get(url)
text = res.text
print(text)

Hello, Chicago.
If there is anyone out there who still doubts that America is a place where all things are possible, who still wonders if the dream of our founders is alive in our time, who still questions the power of our democracy, tonight is your answer.

It's the answer told by lines that stretched around schools and churches in numbers this nation has never seen, by people who waited three hours and four hours, many for the first time in their lives, because they believed that this time must be different, that their voices could be that difference.

It's the answer spoken by young and old, rich and poor, Democrat and Republican, black, white, Hispanic, Asian, Native American, gay, straight, disabled and not disabled. Americans who sent a message to the world that we have never been just a collection of individuals or a collection of red states and blue states.

We are, and always will be, the United States of America.

It's the answer that led those who've been told for so long by

In [5]:
words = text.split()
print(words)

['Hello,', 'Chicago.', 'If', 'there', 'is', 'anyone', 'out', 'there', 'who', 'still', 'doubts', 'that', 'America', 'is', 'a', 'place', 'where', 'all', 'things', 'are', 'possible,', 'who', 'still', 'wonders', 'if', 'the', 'dream', 'of', 'our', 'founders', 'is', 'alive', 'in', 'our', 'time,', 'who', 'still', 'questions', 'the', 'power', 'of', 'our', 'democracy,', 'tonight', 'is', 'your', 'answer.', "It's", 'the', 'answer', 'told', 'by', 'lines', 'that', 'stretched', 'around', 'schools', 'and', 'churches', 'in', 'numbers', 'this', 'nation', 'has', 'never', 'seen,', 'by', 'people', 'who', 'waited', 'three', 'hours', 'and', 'four', 'hours,', 'many', 'for', 'the', 'first', 'time', 'in', 'their', 'lives,', 'because', 'they', 'believed', 'that', 'this', 'time', 'must', 'be', 'different,', 'that', 'their', 'voices', 'could', 'be', 'that', 'difference.', "It's", 'the', 'answer', 'spoken', 'by', 'young', 'and', 'old,', 'rich', 'and', 'poor,', 'Democrat', 'and', 'Republican,', 'black,', 'white,', 

1) 본문에서 'America'가 처음 등장하는 위치를 반환해보세요. 또, 총 몇 번 등장했는지 알 수 있는 코드를 작성해보세요.

- 두 문제 모두 정규표현식을 사용해보세요
- 등장횟수는 **`len()`** 함수를 통해 간단하게 알아낼 수 있겠죠 ???? 다른 방법이 있으시다면 마음껏 적어주세요 !! ㅎ

In [6]:
import re

print(re.search('America',text))

America_count = re.findall('America',text)
print(len(America_count))

<re.Match object; span=(68, 75), match='America'>
25


2) 본문에 '-'가 2번 이상 등장한 경우, 이를 한번으로 대체하는 코드를 작성해보세요.

In [7]:
대체 = re.sub('--','-',text)

3) words에 저장된 list형태의 자료를 활용하여 각 단어의 글자수를 저장한 list를 만들어보세요.
- **`lambda`**를 활용해 보세요
- 일반적인 문자를 찾아주는 정규 표현식을 사용하여 풀어주세요

In [8]:
# 방법1. 반복문
print('방법1. 반복문')
글자수list = []
for i in range(len(words)):
    글자수list.append(len(words[i]))
print(글자수list)

# 방법2. 람다
print('방법2. 람다')
print(list(map(lambda x: len(x), words)))

# 정규 표현식을 사용해서..?

방법1. 반복문
[6, 8, 2, 5, 2, 6, 3, 5, 3, 5, 6, 4, 7, 2, 1, 5, 5, 3, 6, 3, 9, 3, 5, 7, 2, 3, 5, 2, 3, 8, 2, 5, 2, 3, 5, 3, 5, 9, 3, 5, 2, 3, 10, 7, 2, 4, 7, 4, 3, 6, 4, 2, 5, 4, 9, 6, 7, 3, 8, 2, 7, 4, 6, 3, 5, 5, 2, 6, 3, 6, 5, 5, 3, 4, 6, 4, 3, 3, 5, 4, 2, 5, 6, 7, 4, 8, 4, 4, 4, 4, 2, 10, 4, 5, 6, 5, 2, 4, 11, 4, 3, 6, 6, 2, 5, 3, 4, 4, 3, 5, 8, 3, 11, 6, 6, 9, 6, 6, 9, 4, 9, 8, 3, 3, 9, 9, 3, 4, 1, 7, 2, 3, 5, 4, 2, 4, 5, 4, 4, 1, 10, 2, 11, 2, 1, 10, 2, 3, 6, 3, 4, 7, 2, 4, 3, 6, 4, 3, 3, 6, 6, 2, 8, 4, 3, 6, 4, 3, 5, 6, 4, 4, 3, 2, 4, 2, 2, 4, 2, 2, 7, 3, 7, 3, 8, 5, 4, 2, 3, 7, 2, 3, 5, 5, 2, 3, 3, 2, 7, 3, 4, 2, 5, 4, 6, 3, 4, 2, 1, 6, 4, 4, 4, 1, 4, 4, 7, 3, 8, 7, 2, 4, 2, 3, 2, 4, 4, 2, 4, 8, 2, 4, 8, 6, 6, 3, 4, 2, 8, 1, 6, 3, 7, 4, 8, 1, 8, 2, 15, 8, 4, 4, 4, 7, 5, 4, 7, 5, 3, 6, 10, 2, 8, 10, 6, 16, 11, 5, 5, 11, 4, 6, 8, 12, 8, 7, 4, 6, 6, 4, 3, 4, 2, 4, 9, 3, 4, 6, 4, 6, 3, 6, 3, 3, 7, 4, 2, 6, 2, 3, 7, 10, 3, 7, 4, 4, 2, 2, 6, 5, 2, 8, 2, 3, 6, 3, 3, 3, 7, 8, 2, 4, 5, 3, 8, 

#### 4. numpy 모듈 복습하기

1) 정수인 난수를 생성하는 **`random`** 서브모듈을 활용하여 두 자리수 난수를 발생시키고, 이를 `(2,5,3)`의 shape을 가진 배열을 만든 후 `matrix` 라는 변수에 저장해 보세요. (단, 코드를 실행할 때 마다 결과값이 같아야 합니다.)

In [9]:
import numpy as np
np.random.seed(0)
matrix = np.random.randint(10,100, size = (2,3,5))
matrix

array([[[54, 57, 74, 77, 77],
        [19, 93, 31, 46, 97],
        [80, 98, 98, 22, 68]],

       [[75, 49, 97, 56, 98],
        [91, 47, 35, 87, 82],
        [19, 30, 90, 79, 89]]])

2) `matrix`에 저장된 배열을 1차원 배열로 편 후 새로운 변수 `matrix2`에 저장하고, 앞에서 두 번째에 위치한 요소를 15로 바꿔보세요. (단, 원본도 함께 바뀌어야 합니다.)

In [10]:
# matrix2 = matrix.reshape(1,-1)
# matrix2

matrix2 = np.ravel(matrix) # matrix.flatten()은 카피본 사용
matrix2[1] = 15

print(matrix2)
print('')
print(matrix)

[54 15 74 77 77 19 93 31 46 97 80 98 98 22 68 75 49 97 56 98 91 47 35 87
 82 19 30 90 79 89]

[[[54 15 74 77 77]
  [19 93 31 46 97]
  [80 98 98 22 68]]

 [[75 49 97 56 98]
  [91 47 35 87 82]
  [19 30 90 79 89]]]


3) `matrix2`에서 50 이상인 수의 위치값을 반환해 보고, 해당 숫자를 100으로, 그렇지 않으면 10으로 바꿔보세요.

In [11]:
np.where(matrix2 > 50)

(array([ 0,  2,  3,  4,  6,  9, 10, 11, 12, 14, 15, 17, 18, 19, 20, 23, 24,
        27, 28, 29], dtype=int64),)

In [12]:
np.where(matrix2 > 50, 100, 10) # (조건식, 조건에 맞을 때의 값, 다를 때의 값)

array([100,  10, 100, 100, 100,  10, 100,  10,  10, 100, 100, 100, 100,
        10, 100, 100,  10, 100, 100, 100, 100,  10,  10, 100, 100,  10,
        10, 100, 100, 100])