# 5. 넘파이

In [2]:
import numpy as np

In [4]:
np.array([1,2,3])

array([1, 2, 3])

In [5]:
x = np.array([1,2,3])
print(x)

[1 2 3]


In [6]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
x = np.array([[1,2,3,],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(4,10,2)

array([4, 6, 8])

In [12]:
np.linspace(1,10,4) # 4등분

array([ 1.,  4.,  7., 10.])

In [18]:
np.linspace(1,10,20) # 20등분

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [22]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.zeros((2,4,3)) # (page, row, column)

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [5]:
 # np.random.rand : 0과 1 사이의 균일 분포 난수 생성
np.random.rand(5)

array([0.5144262 , 0.79545086, 0.1672428 , 0.48319401, 0.78243615])

In [9]:
np.random.rand(2,3)

array([[0.3556005 , 0.7029746 , 0.81099505],
       [0.84759167, 0.85582092, 0.40656579]])

In [12]:
# np.random.randn : 가우시안 표준 정규 분포 난수 생성
np.random.randn(5)

array([ 2.32796574, -0.4449084 ,  2.3426002 , -0.36477578, -0.28336315])

In [13]:
np.random.randn(2,3)

array([[ 0.64265286, -1.60909257, -1.53272508],
       [ 1.13910418, -0.02485443, -1.52784545]])

In [15]:
 #np.random.randint : 균일 분포의 정수인 난수 생성
np.random.randint(10, size=6)

array([6, 8, 2, 8, 3, 4])

In [19]:
np.random.randint(10,20, size=(2,3))

array([[19, 19, 16],
       [12, 15, 19]])

In [27]:
# 난수값 고정
np.random.seed(0)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [29]:
np.random.seed(3)
np.random.rand(5)

array([0.5507979 , 0.70814782, 0.29090474, 0.51082761, 0.89294695])

In [32]:
np.random.seed(2)
np.random.rand(5)

array([0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ])

In [33]:
arr = np.random.randint(10,20,size=(2,3,3))
print(arr)

[[[12 11 15]
  [14 14 15]
  [17 13 16]]

 [[14 13 17]
  [16 11 13]
  [15 18 14]]]


In [41]:
arr[1]

array([[14, 13, 17],
       [16, 11, 13],
       [15, 18, 14]])

In [42]:
arr[0]

array([[12, 11, 15],
       [14, 14, 15],
       [17, 13, 16]])

In [43]:
arr[1,1,2]

13

In [47]:
arr[1,1,2] = 120
arr

array([[[ 12,  11,  15],
        [ 14,  14,  15],
        [ 17,  13,  16]],

       [[ 14,  13,  17],
        [ 16,  11, 120],
        [ 15,  18,  14]]])

In [48]:
arr[:1,1:,:3]

array([[[14, 14, 15],
        [17, 13, 16]]])

In [62]:
np.random.seed(2)
x = np.random.randint(1,10,8)
print(x)

[9 9 7 3 9 8 3 2]


In [63]:
x[x>3]

array([9, 9, 7, 9, 8])

In [64]:
x[x>3] = 100
print(x)

[100 100 100   3 100 100   3   2]


In [65]:
# np.where : 조건에 맞는 값의 index 반환
np.where(x>3)

(array([0, 1, 2, 4, 5], dtype=int64),)

In [66]:
x[np.where(x>3)]

array([100, 100, 100, 100, 100])

In [71]:
x[[0,1,2,4,5]] #와 같다.

array([100, 100, 100, 100, 100])

In [74]:
np.where(x>3,50, x)

array([50, 50, 50,  3, 50, 50,  3,  2])

In [80]:
b = np.arange(15).reshape(3,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [81]:
np.ravel(b) # 원본 그대로 사용

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [82]:
b.flatten() # copy본 사용

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [86]:
x = np.array([[4,4,4],[8,8,8]])
y = np.array([[1,1,1],[2,2,2]])

print(x+y)
print(x-y)
print(x*y)
print(x/y)

[[ 5  5  5]
 [10 10 10]]
[[3 3 3]
 [6 6 6]]
[[ 4  4  4]
 [16 16 16]]
[[4. 4. 4.]
 [4. 4. 4.]]


In [87]:
x = np.arange(10).reshape(2,5)
y = np.arange(12).reshape(3,4)
print(x+y) # 크기가 다르면 오류 발생

ValueError: operands could not be broadcast together with shapes (2,5) (3,4) 