# 3. 데이터 표준화

In [1]:
import pandas as pd
df = pd.read_csv('auto-mpg.csv', header = None) # 원본데이터에 열 이름이 없기 때문에 header = None
df.columns = ['mpg','cylinders','displacement','horsepower','weight','acceleration','model year','origin','name'] # 칼럼 이름 직접 입력

In [2]:
# 단위 환산
mpg_to_kpl = 1.60934/3.78541 # 갤런당 마일 단위를 리터당 킬로미터 단위로 변환
                             # 1마일은 1.60934km, 1갤런은 3.78541리터. 따라서 1mpg = 0.425km/L

df['kpl'] = df['mpg']*mpg_to_kpl
df.head(3)

mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0      130.0  3504.0          12.0          70   
1  15.0          8         350.0      165.0  3693.0          11.5          70   
2  18.0          8         318.0      150.0  3436.0          11.0          70   

   origin                       name       kpl  
0       1  chevrolet chevelle malibu  7.652571  
1       1          buick skylark 320  6.377143  
2       1         plymouth satellite  7.652571

In [3]:
df['kpl'] = df['kpl'].round(2) # 소수점 아래 둘째자리에서 반올림
df.head(3)

mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0      130.0  3504.0          12.0          70   
1  15.0          8         350.0      165.0  3693.0          11.5          70   
2  18.0          8         318.0      150.0  3436.0          11.0          70   

   origin                       name   kpl  
0       1  chevrolet chevelle malibu  7.65  
1       1          buick skylark 320  6.38  
2       1         plymouth satellite  7.65

In [4]:
# 자료형 변환
df = pd.read_csv('auto-mpg.csv', header = None)
df.columns = ['mpg','cylinders','displacement','horsepower','weight','acceleration','model year','origin','name']

df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight          float64
acceleration    float64
model year        int64
origin            int64
name             object
dtype: object

In [5]:
df['horsepower'].unique()
# 중간에 '?' 가 섞여있어서 문자열로 인식된 것으로 보인다.

array(['130.0', '165.0', '150.0', '140.0', '198.0', '220.0', '215.0',
       '225.0', '190.0', '170.0', '160.0', '95.00', '97.00', '85.00',
       '88.00', '46.00', '87.00', '90.00', '113.0', '200.0', '210.0',
       '193.0', '?', '100.0', '105.0', '175.0', '153.0', '180.0', '110.0',
       '72.00', '86.00', '70.00', '76.00', '65.00', '69.00', '60.00',
       '80.00', '54.00', '208.0', '155.0', '112.0', '92.00', '145.0',
       '137.0', '158.0', '167.0', '94.00', '107.0', '230.0', '49.00',
       '75.00', '91.00', '122.0', '67.00', '83.00', '78.00', '52.00',
       '61.00', '93.00', '148.0', '129.0', '96.00', '71.00', '98.00',
       '115.0', '53.00', '81.00', '79.00', '120.0', '152.0', '102.0',
       '108.0', '68.00', '58.00', '149.0', '89.00', '63.00', '48.00',
       '66.00', '139.0', '103.0', '125.0', '133.0', '138.0', '135.0',
       '142.0', '77.00', '62.00', '132.0', '84.00', '64.00', '74.00',
       '116.0', '82.00'], dtype=object)

In [6]:
# 누락데이터('?') 삭제
import numpy as np
df['horsepower'].replace('?', np.nan, inplace = True)
df.dropna(subset = ['horsepower'], axis = 0, inplace = True)
df['horsepower'] = df['horsepower'].astype('float')

print(df['horsepower'].dtypes)

float64


In [7]:
df['horsepower'].unique()

array([130., 165., 150., 140., 198., 220., 215., 225., 190., 170., 160.,
        95.,  97.,  85.,  88.,  46.,  87.,  90., 113., 200., 210., 193.,
       100., 105., 175., 153., 180., 110.,  72.,  86.,  70.,  76.,  65.,
        69.,  60.,  80.,  54., 208., 155., 112.,  92., 145., 137., 158.,
       167.,  94., 107., 230.,  49.,  75.,  91., 122.,  67.,  83.,  78.,
        52.,  61.,  93., 148., 129.,  96.,  71.,  98., 115.,  53.,  81.,
        79., 120., 152., 102., 108.,  68.,  58., 149.,  89.,  63.,  48.,
        66., 139., 103., 125., 133., 138., 135., 142.,  77.,  62., 132.,
        84.,  64.,  74., 116.,  82.])

In [8]:
#  Origin 열에는 정수형 데이터인 1, 2, 3이 들어있지만 실제로는 국가 이름인 USA, EU, JPN을 뜻한다.
print(df['origin'].unique())

[1 3 2]


In [9]:
df['origin'].replace({1:'USA',2:'EU',3:'JPN'},inplace = True)
print(df['origin'].unique())
print(df['origin'].dtype)

['USA' 'JPN' 'EU']
object


In [10]:
# 유한 개의 고유값이 반복적으로 나타나는 경우 범주형(category) 데이터로 표현하는 것이 효율적이다.
df['origin'] = df['origin'].astype('category')
print(df['origin'].dtypes)

df['origin'] = df['origin'].astype('str')
print(df['origin'].dtypes)

category
object


In [11]:
print(df['model year'].sample(3)) # sample 메서드로 무작위로 3개 행 선택
# 연도를 뜻하기 때문에 숫자형으로 남겨도 무방하지만,
# 연도는 시간적인 순서의 의미는 있으나 숫자의 상대적인 크기는 별 의미가 없기 때문에 범주형으로 표현하는 것이 적절하다.

df['model year'] = df['model year'].astype('category')
print(df['model year'].sample(3))

145    74
223    77
268    78
Name: model year, dtype: int64
118    73
189    76
17     70
Name: model year, dtype: category
Categories (13, int64): [70, 71, 72, 73, ..., 79, 80, 81, 82]


# 4. 범주형(카테고리) 데이터 처리

In [13]:
# 연속형 데이터를 그대로 사용하기 보다는 일정한 구간(bin)으로 나눠서 분석하는 것이 효율적인 경우가 있다.
# cut() 함수를 이용하면 연속형 데이터를 여러 구간으로 나누고 범주형 데이터로 변환할 수 있다,

import pandas as pd
import numpy as np

df = pd.read_csv('auto-mpg.csv', header = None)

df.columns = ['mpg','cylinders','displacement','horsepower','weight','acceleration','model year','origin','name']

df['horsepower'].replace('?', np.nan, inplace = True)
df.dropna(subset = ['horsepower'], axis = 0, inplace = True)
df['horsepower'] = df['horsepower'].astype('float')

count, bin_dividers = np.histogram(df['horsepower'], bins = 3) # 나누려는 구간(bin) 개수를 bins 옵션에 입력하면 
                                                                # 각 구간에 속하는 값의 개수(count)와 
                                                                # 경계값 리스트(bin_dividers)를 반환한다.
print(count)
print(bin_dividers)

[257 103  32]
[ 46.         107.33333333 168.66666667 230.        ]


In [14]:
bin_names = ['저출력','보통출력','고출력']

df['hp_bin'] = pd.cut(x = df['horsepower'], # 데이터 배열
                     bins = bin_dividers,
                     labels = bin_names,
                     include_lowest = True) # 각 구간의 낮은 경계값을 포함

print(df[['horsepower','hp_bin']].head(15))

    horsepower hp_bin
0        130.0   보통출력
1        165.0   보통출력
2        150.0   보통출력
3        150.0   보통출력
4        140.0   보통출력
5        198.0    고출력
6        220.0    고출력
7        215.0    고출력
8        225.0    고출력
9        190.0    고출력
10       170.0    고출력
11       160.0   보통출력
12       150.0   보통출력
13       225.0    고출력
14        95.0    저출력


### 인코딩 (파이썬 머신러닝 완벽 가이드)

In [15]:
# LabelEncoder
from sklearn.preprocessing import LabelEncoder

items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값:',labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]


In [16]:
print('인코딩 클래스:', encoder.classes_) # 0번부터 순서대로 어떤 문자열이 어떤 숫자로 변환된 것인지

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [17]:
print('디코딩 원본값:', encoder.inverse_transform([4,5,2,0,1,1,3,3]))

디코딩 원본값: ['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


In [18]:
# 그러나 데이터가 매우 많을 경우 어떤 문자열이 어떤 숫자로 변환되었는지 알기 어렵다.
# 회귀와 같은 머신러닝 알고리즘에서 숫자값의 크고 작음에 대한 특성이 작용하여 예측 성능이 저하될 우려

In [19]:
# One-Hot encoder
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

# 2차원 데이터로 변환
labels = labels.reshape(-1,1) # x행 1열

# 원핫 인코딩 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


In [39]:
# get_dummies()
import pandas as pd
df = pd.DataFrame({'item' : 
                   ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']})
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

### 피처 스케일링 (파이썬 머신러닝 완벽 가이드)
서로 다른 변수의 값 범위나 데이터의 피처를 동일한 수준으로 맞추는 작업.

표준화와 정규화가 대표적
- 표준화 : 데이터의 피처 각각이 평균이 0, 분산이 1인 가우시안 정규 분포를 가진 값으로 변환하는 것

In [22]:
from sklearn.datasets import load_iris

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data = iris_data, columns = iris.feature_names)
print('<데이터의 평균 값>')
print(iris_df.mean())
print('\n<데이터의 분산 값>')
print(iris_df.var())

<데이터의 평균 값>
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

<데이터의 분산 값>
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [ ]:
# 평균과 분산이 모두 다르고 가우시안 정규분포를 따르지도 않아 표준화가 필요하다.

In [33]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df) # transfrom 하면 ndarray 형식으로 변환됨

# DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data = iris_scaled, columns = iris.feature_names)

print('<데이터의 평균 값>')
print(iris_df_scaled.mean())
print('\n<데이터의 분산 값>')
print(iris_df_scaled.var())

<데이터의 평균 값>
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

<데이터의 분산 값>
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


- 정규화 : 각 피처를 동일한 크기 단위로 비교하기 위해 모두 최소0 최대1의 값으로 변환해주는 것

In [36]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_df_scaled = pd.DataFrame(data=iris_scaled,columns = iris.feature_names)

print('<데이터의 최대값>')
print(iris_df_scaled.max())
print('\n<데이터의 최소값>')
print(iris_df_scaled.min())

<데이터의 최대값>
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64

<데이터의 최소값>
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64


In [37]:
# 각 열의 데이터를 각 열의 데이터의 최댓값의 절대값으로 나누는 방법
iris_df_abs_scaled = iris_df/abs(iris_df.max())
print('<데이터의 최대값>')
print(iris_df_abs_scaled.max())
print('\n<데이터의 최소값>')
print(iris_df_abs_scaled.min())

<데이터의 최대값>
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64

<데이터의 최소값>
sepal length (cm)    0.544304
sepal width (cm)     0.454545
petal length (cm)    0.144928
petal width (cm)     0.040000
dtype: float64


- 벡터 정규화 : 어떤 벡터를 단위 벡터u(크기가 1인 벡터)로 만드는 작업

벡터를 벡터 자기 자신의 크기(Norm)로 나눠주면 된다.

In [26]:
import numpy as np
an_array = np.random.rand(10)*10 # (0,1) 사이의 난수를 추출하고 각 난수에 10을 곱한 배열 생성
print('<원 배열>\n',an_array)
norm = np.linalg.norm(an_array) # np.linalg.norm()은 벡터의 Norm을 구하는 numpy 함수
print('<원 배열의 Norm>\n', norm)
normal_array = an_array/norm # 원 배열의 norm으로 원 배열읠 나눠서 벡터 정규화 진행(벡터 정규화 공식)
print('<벡터 정규화된 배열>\n', normal_array)
print('<벡터 정규화된 배열의 Norm>\n',np.linalg.norm(normal_array))

<원 배열>
 [8.44225678 8.40960725 9.9885543  5.92346126 6.95854043 1.98104648
 8.04283333 9.78859081 1.471274   8.0869904 ]
<원 배열의 Norm>
 23.606468880110455
<벡터 정규화된 배열>
 [0.35762472 0.35624164 0.42312784 0.25092534 0.29477261 0.08391964
 0.34070463 0.41465714 0.06232504 0.34257518]
<벡터 정규화된 배열의 Norm>
 1.0


In [27]:
iris_df_vector_scaled = iris_df / np.linalg.norm(iris_df)
print('<벡터 정규화된 데이터의 최댓값>')
print(iris_df_vector_scaled.max())
print('\n<벡터 정규화된 데이터의 최솟값>')
print(iris_df_vector_scaled.min())
print('\n<원 데이터 프레임의 Norm>',np.linalg.norm(iris_df))
print('\n<벡터 정규화된 데이터 프레임의 Norm>',np.linalg.norm(iris_df_vector_scaled))

<벡터 정규화된 데이터의 최댓값>
sepal length (cm)    0.080885
sepal width (cm)     0.045050
petal length (cm)    0.070647
petal width (cm)     0.025597
dtype: float64

<벡터 정규화된 데이터의 최솟값>
sepal length (cm)    0.044026
sepal width (cm)     0.020477
petal length (cm)    0.010239
petal width (cm)     0.001024
dtype: float64

<원 데이터 프레임의 Norm> 97.66928892952994

<벡터 정규화된 데이터 프레임의 Norm> 1.0


In [31]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

# 학습 데이터는 0에서 10까지, 테스트 데이터는 0에서 10까지 값을 가지는 데이터 세트로 생성
# Sclaer 클래스의 fit(), transform()은 2차원 이상 데이터만 가능하므로 reshape(-1,1)로 차원 변환
train_array = np.arange(0,11).reshape(-1,1)
test_array = np.arange(0,6).reshape(-1,1)

scaler = MinMaxScaler()
scaler.fit(train_array)

train_scaled = scaler.transform(train_array)

print('원본 train_array 데이터:',np.round(train_array.reshape(-1),2))
print('Scale된 train_array 데이터:',np.round(train_scaled.reshape(-1),2))

원본 train_array 데이터: [ 0  1  2  3  4  5  6  7  8  9 10]
Scale된 train_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [29]:
scaler.fit(test_array)
test_scaled = scaler.transform(test_array)
print('원본 test_array 데이터:',np.round(test_array.reshape(-1),2))
print('Scale된 test_array 데이터:',np.round(test_scaled.reshape(-1),2))

원본 test_array 데이터: [0 1 2 3 4 5]
Scale된 test_array 데이터: [0.  0.2 0.4 0.6 0.8 1. ]


In [32]:
test_scaled = scaler.transform(test_array)
print('원본 test_array 데이터:',np.round(test_array.reshape(-1),2))
print('Scale된 test_array 데이터:',np.round(test_scaled.reshape(-1),2))

원본 test_array 데이터: [0 1 2 3 4 5]
Scale된 test_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5]
